# will run three jobs that depend one each other and the condition to run is every pull request.
# The first job will print "Hello from Job 1",
# the second job will print "Hello from Job 2",
# and the third will print "Hello from Job 3". 
# Constraints: job two only will run if the file skip.txt is modified if not can be skipped,
# and job 3 will always run no matter if job 2 doesn't run

name: Dependency Pipeline

on:
  pull_request: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    branches:
        - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from Job 1
        run: echo "Hello from Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ contains(github.event.pull_request.files.*.filename, 'skip.txt') }}
    steps:
      - name: Print Hello from Job 2
        run: echo "Hello from Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Print Hello from Job 3
        run: echo "Hello from Job 3"
